{
 "title": "Logs",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total of transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "counter.value", "id": "1", "type": "rate" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Avarage Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "gauge.value", "id": "1", "type": "avg" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "status_code Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tags.status_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tags.status_code:200",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "tags.status_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tags.status_code:300",
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      {
       "field": "tags.status_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tags.status_code:500",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Count status_code: 500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tags.status_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "counter.value", "id": "1", "type": "sum" }
     ],
     "query": "tags.status_code:500",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Count status_code: 200",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "counter.value", "id": "1", "type": "sum" }
     ],
     "query": "tags.status_code:200",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Count status_code: 300",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tags.status_code.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "counter.value", "id": "1", "type": "sum" }
     ],
     "query": "tags.status_code:300",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}